Face_Analyzer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.urls import re_path
from app import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Face Detection app/', include('app.urls')),
    path('', RedirectView.as_view(url='/Face Detection app/', permanent=True)),
    re_path(r'^media/<path:path>$', views.media),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import re_path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    re_path(r'$', views.mainClass.as_view(), name='main'),
    re_path(r'signup/$', views.signup_view, name='signup'),
    re_path(r'login/$', views.login_view, name='login'),
    re_path(r'logout/$', LogoutView.as_view(next_page='/'), name='logout'),
    re_path("password_reset/$", views.ResetPasswordView.as_view(), name="password_reset"),
    re_path(r'analize/$', views.analize_view, name='analize_file'),
    re_path(r'my-results/$', views.MyResultsListView.as_view(), name='my_results'),
    re_path(r'my-results/(?P<pk>\d+)$', views.MediaDetailView.as_view(), name='media_detail'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    image = models.ImageField(default='default.png ', upload_to='avatars/')
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=150, unique=True)
    REQUIRED_FIELDS = ['email','password']

    def __str__(self):
        return self.username if self.username else 'No username'

class MediaFile(models.Model):
    FILE_TYPES = [
        ('image', 'Image'),
        ('video', 'Video'),
    ]
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,related_name='files')
    start_file = models.FileField()
    end_file = models.FileField(null=True, blank=True)
    landmarks_file = models.FileField(null=True, blank=True)
    file_type = models.CharField(max_length=10, choices=FILE_TYPES)
    file_name = models.CharField(max_length=120)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    processed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.file_name} ({self.file_type})"

class DetectedFace(models.Model):
    media = models.ForeignKey(MediaFile, on_delete=models.CASCADE, related_name='faces')
    timestamp = models.FloatField(null=True, blank=True)  # Для видео (в секундах), null для изображений
    name = models.CharField(max_length=120)
    data = models.JSONField()

    def __str__(self):
        return f"Face in {self.media.file_name} @ {self.name}"

class Emotion(models.Model):
    face = models.ForeignKey(DetectedFace, on_delete=models.CASCADE, related_name='emotions')
    type = models.CharField(max_length=20)  # например: 'HAPPY', 'SAD', ...
    confidence = models.FloatField()

    def __str__(self):
        return f"{self.face} {self.type} ({self.confidence:.2f}%)"

catalog/views.py
from typing import cast

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.http import JsonResponse
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
# from django.core.mail import send_mail, BadHeaderError
# from django.http import HttpResponse
#
# from Habr.settings import DEFAULT_FROM_EMAIL, RECIPIENTS_EMAIL

from django.views.static import serve
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate

from Face_Analyzer.analize import analize_emotions, analize_landmarks
from . import models
from .forms import SignUpForm, LoginForm

from .models import MediaFile, CustomUser

import logging
import numpy as np


def clean_for_json(obj):
    if isinstance(obj, dict):
        return {k: clean_for_json(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [clean_for_json(i) for i in obj]
    elif isinstance(obj, tuple):
        return list(obj)  # JSON не поддерживает tuple
    elif isinstance(obj, (np.float32, np.float64)):
        return round(float(obj), 2)  # Округляем до двух знаков после запятой
    elif isinstance(obj, (np.int32, np.int64)):
        return int(obj)
    else:
        return obj

logger = logging.getLogger('django')
def media(request, path):
    return serve(request, path, document_root=settings.MEDIA_ROOT)

class mainClass(View):
    def get(self, request):
        return render(request,'catalog/main_template.html')
def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main')
    else:
        form = SignUpForm()
    return render(request, 'catalog/registration/signup.html', {'form': form})

def login_view(request):
    form = LoginForm(data=request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('main')
    return render(request, 'catalog/registration/login.html', {'form': form})

class ResetPasswordView(PasswordResetView):
    pass

def analize_view(request):
    if request.method == 'POST':
        uploaded_file = request.FILES.get('file')
        file_type =''
        if not uploaded_file:
            return JsonResponse({'error': 'No file uploaded'}, status=400)
        content_type = uploaded_file.content_type
        if content_type.startswith('image/'):
            file_type = 'image'
        elif content_type.startswith('video/'):
            file_type = 'video'
        else :
            return JsonResponse({'error': 'Unsupported file type'}, status=400)

        path = default_storage.save(f'uploads/{uploaded_file.name}', ContentFile(uploaded_file.read()))
        filename = path.split('/')[-1]
        logger.info(f'File PATH: { path}')
        user = cast(CustomUser, request.user)
        file = MediaFile.objects.create(start_file=path,file_type=file_type,file_name=filename,user = user)
        try:
            new_file_data = analize_emotions(file)
            new_file=new_file_data['media_path'].split('media/')[-1]
            data = new_file_data['data']
            count = len(data)
            logger.info(f'NewFile PATH: {new_file}')
            file.end_file = new_file
            file.processed = True

            msg=''
            if count ==1:
                msg='найдено лицо'
            else :
                msg='найдены лица'

            landmarks_data = analize_landmarks(file)
            file_landmarks = landmarks_data['media_path'].split('media/')[-1]

            file.landmarks_file = file_landmarks

            file.save()
            clear_data= clean_for_json(data)
            for face in clear_data:
                id = face['Id']
                Face = models.DetectedFace.objects.create(media=file,name=f'face {id}',data=face)
                for emotion_type, val in face['emotion'].items():
                    Emotion = models.Emotion.objects.create(face=Face,type=emotion_type,confidence=val)
            return JsonResponse({'face_data':clear_data,
                                 'message': f'{msg}',
                                 'end_file_path': settings.MEDIA_URL+new_file,
                                 'start_file_path': settings.MEDIA_URL+path,
                                 'count_faces': count,
                                 'file_landmarks': settings.MEDIA_URL+file_landmarks})
        except ValueError as e:
            return JsonResponse({'error': str(e)}, status=422)
        except Exception as e:
            logger.error(f"Ошибка обработки: {str(e)}", exc_info=True)
            return JsonResponse({'error': str(e)}, status=500)


class MyResultsListView(LoginRequiredMixin, ListView):
    model = MediaFile
    template_name = 'catalog/my_results.html'
    context_object_name = 'media_files'

    def get_queryset(self):
        return MediaFile.objects.filter(user=self.request.user).order_by('-uploaded_at')


class MediaDetailView(LoginRequiredMixin, DetailView):
    model = MediaFile
    template_name = 'catalog/media_detail.html'
    context_object_name = 'media'

    def get_queryset(self):
        return MediaFile.objects.filter(user=self.request.user)

catalog/templates/catalog/base.html
{% extends 'base.html' %}
    
{% block sidebar %}
    {% include 'catalog/partials/sidebar.html' %}
    
{% endblock  %}

{% block content %}

{% endblock %}

catalog/templates/catalog/email.html
{% extends 'catalog/base.html' %}
{% block content %}
  <div class="form-container">
  <h2 >Оставьте заявку</h2>
    <div id="form-group">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-actions form-group ">
          <button type="submit" class="button">Отправить</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/main_template.html
{% extends 'catalog/base.html' %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
<div class="main-container">
    <div class="top-section">
        <div class="upload-container">
            <div class="upload-area" id="upload-area">
              <p id="drag_a_drop">Перетащите файл сюда<br>или нажмите для выбора</p>
              <input type="file" id="file-input" accept="image/*,video/*" hidden>

              <div class="preview" id="preview">
                <button class="remove-preview" id='remove_btn' onclick="event.stopPropagation(); removePreview();resetFileInput()">×</button>
                <img id="img-preview" src="#" alt="" style="display:none;">
                <video id="video-preview" controls style="display:none;"></video>
                <div class="filename" id="filename"></div>
              </div>
            </div>

            <button class="analyze-btn" id="analyze-btn">
              🔍 Анализировать лицо
            </button>
        </div>

        <div class="card features-card">
            <h3>Основные возможности</h3>
            <ul class="features-list">
                <li><strong>Анализ эмоций</strong><br>Распознавание счастья, грусти, удивления и др.</li>
                <li><strong>Пол и возраст</strong><br>Определение пола и приблизительного возраста</li>
                <li><strong>Анализ расы</strong><br>Определение расы такой как indian, white, black и др.<br></li>
                <li><strong>Ключевые точки лица</strong><br>Детальная разметка черт лица</li>
            </ul>
        </div>
    </div>

    <div class="card result-card">
        <h3>Результаты анализа лица</h3>
        <div class="result-container" id="results" style="display: none;">
          <div class="result-header">
            <div class="face-count" id="faces-count">0</div>
            <div>Обнаружено лиц</div>
          </div>

         <div class="data-container">
              <div class="btn-group-2">
                <button class="tab-btn active" onclick="showSection('media', this)">
                  <i class="fas fa-photo-film"></i> Медиа
                </button>
                <button class="tab-btn" onclick="showSection('facedata', this)">
                  <i class="fas fa-user"></i> Данные лица
                </button>
                <button class="tab-btn" onclick="showSection('landmarks', this)">
                  <i class="fas fa-map-marked-alt"></i> Ключевые точки
                </button>
              </div>

              <!-- Контейнер: Media -->
              <div id="section-media" class="section-block">
                <div class="images">
                  <div class="image-block">
                    <div class="image-title">Оригинал</div>
                    <img id="original-img" src="" alt="Оригинальное изображение">
                  </div>
                  <div class="image-block">
                    <div class="image-title">Обработанный результат</div>
                    <img id="processed-img" src="" alt="Обработанное изображение">
                  </div>
                </div>
              </div>
              <!-- Контейнер: FaceData -->
                <div id="section-facedata" class="section-block" style="display: none;">
                  <table class="face-table">
                    <thead>
                      <tr>
                        <th>ID лица</th>
                        <th>Пол</th>
                        <th>Возраст</th>
                        <th>Главная эмоция</th>
                        <th>Действия</th>
                      </tr>
                    </thead>
                    <tbody>
                    </tbody>
                  </table>
                </div>

              <!-- Контейнер: Landmarks -->
              <div id="section-landmarks" class="section-block" style="display: none;">
                 <div class="image-block">
                    <div class="image-title">Ключевые точки</div>
                    <img id="landmark-img" src="" alt="Изображение с точками">
                  </div>
              </div>
                    <!-- Модальное окно -->
                <div id="face-modal" class="modal" style="display:none;">
                  <div class="modal-content">
                    <span class="close-btn">&times;</span>
                    <div id="modal-details"></div>
                  </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script>
    const uploadArea = document.getElementById('upload-area');
    const fileInput = document.getElementById('file-input');
    const preview = document.getElementById('preview');
    const imgPreview = document.getElementById('img-preview');
    const videoPreview = document.getElementById('video-preview');
    const filenameText = document.getElementById('filename');
    const analyzeBtn = document.getElementById('analyze-btn');
    const drgDrp = document.getElementById('drag_a_drop');
    const removeBtn = document.getElementById('remove_btn');

    // click to open file dialog
    uploadArea.addEventListener('click', () => fileInput.click());

    // handle dropped file
    uploadArea.addEventListener('dragover', e => {
      e.preventDefault();
      uploadArea.classList.add('dragover');
    });

    uploadArea.addEventListener('dragleave', () => {
      uploadArea.classList.remove('dragover');
    });

    uploadArea.addEventListener('drop', e => {
      e.preventDefault();
      uploadArea.classList.remove('dragover');
      const file = e.dataTransfer.files[0];
      handleFile(file);
    });

    fileInput.addEventListener('change', () => {
      const file = fileInput.files[0];
      handleFile(file);
    });
  function handleFile(file) {
      if (!file) return;

      const allowedTypes = ['image/', 'video/'];
      const isAllowed = allowedTypes.some(type => file.type.startsWith(type));

    if (!isAllowed) {
        alert("Разрешены только изображения и видеофайлы!");
        resetFileInput();  // Очистим input, чтобы можно было выбрать другой файл
        return;
    }
      // Сброс предыдущего превью
      removePreview();
      drgDrp.style.display = 'none';
      const url = URL.createObjectURL(file);
      filenameText.textContent = `${file.name} (${(file.size / (1024 * 1024)).toFixed(1)} MB)`;

      if (file.type.startsWith('image')) {
        imgPreview.src = url;
        imgPreview.style.display = 'block';
      } else if (file.type.startsWith('video')) {
        videoPreview.src = url;
        videoPreview.style.display = 'block';
      }

      preview.style.display = 'flex';
      analyzeBtn.style.display = 'inline-block';


  }
   analyzeBtn.addEventListener('click', async () => {
        analyzeBtn.textContent = '⏳ Файл в обработке...';
        analyzeBtn.disabled = true;

        const file = fileInput.files[0];
        if (!file) {
            alert("Файл не выбран");
            return;
        }

        const formData = new FormData();
        formData.append("file", file);
        try {
            removeBtn.style.visibility='hidden';
            const response = await fetch("{% url 'analize_file' %}", {
            method: "POST",
            headers: {
                "X-CSRFToken": getCSRFToken()
            },
            body: formData
        });

            const data = await response.json();

            if (!response.ok) {
                alert('Ошибка: ' + data.error);
                removePreview();
                 removeBtn.style.visibility='visible';
            } else {
                alert('Успех: ' + data.message);
                 setTimeout(() => {
                removePreview();
                removeBtn.style.visibility='visible';

                analyzeBtn.textContent = '✅ Анализ завершен!';
            }, 2000);
                document.getElementById('processed-img').src = data.end_file_path;
                document.getElementById('original-img').src = data.start_file_path;
                document.getElementById('faces-count').innerText = data.count_faces;
                document.getElementById('results').style.display = 'block';
                document.getElementById('landmark-img').src = data.file_landmarks;
                show_table_data(data);
            }
        }
       catch (error) {
        console.error('Сетевая ошибка:', error);

        // Попробуем вывести дополнительные сведения
        if (error instanceof SyntaxError) {
            console.error('Ошибка синтаксиса JSON:', error.message);
        } else if (error instanceof TypeError) {
            console.error('Типовая ошибка (например, fetch не удался):', error.message);
        } else {
            console.error('Общая ошибка:', error.message);
        }


        if (error.response) {
            console.error('Ответ сервера:', error.response.status, error.response.statusText);
            console.error('Данные ответа:', error.response.data);
        }

    removePreview();
    removeBtn.style.visibility = 'visible';
    alert('Произошла ошибка при отправке запроса. Подробнее см. в консоли.');
}

  });

    function getCSRFToken() {
        return document.cookie
            .split(";")
            .find(cookie => cookie.trim().startsWith("csrftoken="))
            ?.split("=")[1];
    }
    function removePreview() {
      imgPreview.src = '#';
      imgPreview.style.display = 'none';

      videoPreview.src = '';
      videoPreview.load(); // для корректного сброса
      videoPreview.style.display = 'none';

      filenameText.textContent = '';
      preview.style.display = 'none';
      analyzeBtn.style.display = 'none';
      analyzeBtn.textContent = '📊 Анализировать файл';
      analyzeBtn.disabled = false;
      drgDrp.style.display = 'block';


    }
    function resetFileInput() {
        fileInput.value = '';
    }
    function showSection(sectionId, btn) {
      // Скрыть все секции
      document.querySelectorAll('.section-block').forEach(section => {
        section.style.display = 'none';
      });

      // Показать нужную
      const target = document.getElementById(`section-${sectionId}`);
      if (target) target.style.display = 'block';

      // Обновить активную кнопку
      document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
    }
    function show_table_data(data) {
    const faceDataContainer = document.getElementById('section-facedata');
    faceDataContainer.innerHTML = '';

    const table = document.createElement('table');
    table.className = 'face-table';

    table.innerHTML = `
      <thead>
        <tr>
          <th>ID лица</th>
          <th>Пол</th>
          <th>Возраст</th>
          <th>Преобладающая эмоция</th>
          <th>Действия</th>
        </tr>
      </thead>
      <tbody>
        ${data.face_data.map((face, index) => `
          <tr data-index="${index}">
            <td>${face.Id}</td>
            <td>${face.dominant_gender}</td>
            <td>${face.age}</td>
            <td><strong>${face.dominant_emotion}</strong> ${face.emotion[face.dominant_emotion]}%</td>
            <td><button class="details-btn">🔍 Подробнее</button></td>
          </tr>
        `).join('')}
      </tbody>
    `;
    faceDataContainer.appendChild(table);

    const buttons = table.querySelectorAll('.details-btn');
    buttons.forEach(btn => {
        btn.addEventListener('click', (e) => {
            const index = e.target.closest('tr').dataset.index;
            const face = data.face_data[index];
            showModalDetails(face);
        });
    });
}

function showModalDetails(face) {
    const modal = document.getElementById('face-modal');
    const details = document.getElementById('modal-details');

    const emotionsHTML = Object.entries(face.emotion).map(([emotion, value]) => `
        <div><strong>${emotion}</strong>: ${value}%</div>
    `).join('');

    const raceHTML = face.race ? `
        <h4>Раса:</h4>
        <p><strong>Преобладающая:</strong> ${face.dominant_race}</p>
        ${Object.entries(face.race).map(([race, value]) => `
            <div><strong>${race}</strong>: ${value}%</div>
        `).join('')}
    ` : '<p>Нет данных о расе</p>';

    details.innerHTML = `
        <h3>Анализ лица №${face.Id}</h3>
        <p><strong>Пол:</strong> ${face.dominant_gender}</p>
        <p><strong>Возраст:</strong> ${face.age}</p>
        <p><strong>Преобладающая эмоция:</strong> ${face.dominant_emotion}</p>

        <div style="display: flex; gap: 30px;">
            <div>
                <h4>Эмоции:</h4>
                ${emotionsHTML}
            </div>
            <div>
                ${raceHTML}
            </div>
        </div>
    `;

    modal.style.display = 'flex';

    modal.querySelector('.close-btn').onclick = () => {
        modal.style.display = 'none';
    };
}

  </script>


{% endblock %}

catalog/templates/catalog/media_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
{% load static %}
{% load dict_extras %}
 <div class="container">
  <h2>Детали анализа</h2>

  <div class="section">
    <h3>Файл</h3>
    <p><strong>Имя:</strong> {{ media.file_name }}</p>
    <p><strong>Тип:</strong> {{ media.get_file_type_display }}</p>
    <p><strong>Дата загрузки:</strong> {{ media.uploaded_at|date:"Y-m-d H:i" }}</p>

    {% if media.start_file %}
      <p><strong>Исходный файл:</strong>
        <a href="{{ media.start_file.url }}" target="_blank">Открыть</a>
      </p>
    {% endif %}
    {% if media.end_file %}
      <p><strong>Обработанный файл:</strong>
        <a href="{{ media.end_file.url }}" target="_blank">Открыть</a>
      </p>
    {% endif %}
    {% if media.landmarks_file %}
      <p><strong>Файл с разметкой:</strong>
        <a href="{{ media.landmarks_file.url }}" target="_blank">Открыть</a>
      </p>
    {% endif %}
  </div>

  <div class="section">
    <h3>Распознанные лица ({{ media.faces.count }})</h3>
    {% if media.faces.exists %}
      <table class="face-table">
        <thead>
          <tr>
            <th>Имя</th>
            <th>Время (если видео)</th>
            <th>Пол</th>
            <th>Возраст</th>
            <th>Топ эмоция</th>
            <th>Действия</th>
          </tr>
        </thead>
        <tbody>
          {% for face in media.faces.all %}
            {% with face_data=face.data %}
              <tr>
                <td>{{ face.name }}</td>
                <td>{% if face.timestamp %}{{ face.timestamp }} c{% else %}—{% endif %}</td>
                <td>{{ face_data.dominant_gender }}</td>
                <td>{{ face_data.age }}</td>
                <td>{{ face_data.dominant_emotion }} ({{ face_data.emotion|get_item:face_data.dominant_emotion }}%)</td>
                <td>
                  <button class="details-btn" onclick="showDetails({{ face.pk }})">🔍 Details</button>
                </td>
              </tr>
              <tr id="details-{{ face.pk }}" style="display:none;">
                  <td colspan="6">
                    <div class="details-columns">
                      <div class="column">
                        <h4>Эмоции:</h4>
                        {% for emotion, val in face_data.emotion.items %}
                          <div><strong>{{ emotion }}</strong>: {{ val }}%</div>
                        {% endfor %}
                      </div>

                      <div class="column">
                        <h4>Раса:</h4>
                        <p><strong>Топ:</strong> {{ face_data.dominant_race }}</p>
                        {% for race, val in face_data.race.items %}
                          <div><strong>{{ race }}</strong>: {{ val }}%</div>
                        {% endfor %}
                      </div>
                    </div>
                  </td>
                </tr>


            {% endwith %}
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>Лица не найдены.</p>
    {% endif %}
  </div>
</div>

<script>
  function showDetails(id) {
    const row = document.getElementById('details-' + id);
    row.style.display = (row.style.display === 'none') ? 'table-row' : 'none';
  }
</script>
{% endblock %}

catalog/templates/catalog/my_results.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
  <h2>Мои файлы</h2>

  {% for file in media_files %}
    <div class="file-card" style="margin-bottom: 20px;">
      {% if file.file_type == 'image' and file.start_file %}
        <div class="file-thumb">
          <img src="{{ file.start_file.url }}" alt="{{ file.file_name }}" style="max-width: 200px; max-height: 150px; object-fit: cover;">
        </div>
      {% elif file.file_type == 'video' and file.start_file %}
        <div class="file-thumb">
          <video width="200" height="150" controls>
            <source src="{{ file.start_file.url }}" type="video/mp4">
            Ваш браузер не поддерживает видео.
          </video>
        </div>
      {% endif %}

      <div class="file-meta">
        <span>{{ file.uploaded_at|date:"Y-m-d H:i" }}</span>
        <span class="file-type">{{ file.get_file_type_display }}</span>
        <span>{{ file.file_name }}</span>
      </div>

      <a href="{% url 'media_detail' file.pk %}">Детали ›</a>
    </div>
  {% empty %}
    <p>У вас пока нет файлов.</p>
  {% endfor %}
</div>
{% endblock %}